repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.0
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff linter
      - id: ruff
        name: ruff sorter
        description: "Run 'ruff' for extremely fast Python imports sorting"
        args: [ --select, I, --fix ]
      # Run the formatter.
      - id: ruff-format
        name: ruff formater
